name: Run e2e Tests

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - '5432:5432'
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: gympass-clone

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - run: pnpm install

      - run: pnpm test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/gympass-clone?schema=public'
