name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    # Rodar o node.js
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm ci

      - run: pnpm test
